services:
  nginx:
    image: jerem0027/server:nginx-1.27.0
    container_name: nginx
    networks:
      - website-network
    restart: unless-stopped
    volumes:
      - ~/Documents/web_site/html:/etc/nginx/html
      - ./certs/:/ssl/
      - ./www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    links:
      - php
      - mariadb
      - phpmyadmin
      - certbot

  php:
    image: jerem0027/server:php-8.3.8
    container_name: php
    networks:
      - website-network
    restart: unless-stopped
    volumes:
      - ~/Documents/web_site/html:/etc/nginx/html
    env_file:
      - configs/php.env
    links:
      - mariadb

  mariadb:
    image: jerem0027/server:mariadb-10.11.8
    container_name: mariadb
    networks:
      - website-network
    restart: unless-stopped
    volumes:
      - db_content:/var/lib/mysql
    env_file:
      - configs/mariadb.env
    ports:
      - 3306:3306

  phpmyadmin:
    image: jerem0027/server:phpmyadmin-5.2.1
    container_name: phpmyadmin
    networks:
      - website-network
    restart: unless-stopped
    volumes:
      - ./certs/:/etc/apache2/ssl/
    env_file:
      - configs/phpmyadmin.env
    links:
      - mariadb

  certbot:
    image: certbot/certbot:v2.11.0
    container_name: certbot
    networks:
        - website-network
    restart: unless-stopped
    volumes:
        - ./certs:/etc/letsencrypt
        - ./www:/var/www/certbot
        - ./certbot.sh:/certbot.sh
    entrypoint: /bin/sh /certbot.sh

volumes:
  db_content:

networks:
  website-network:
      # external: true
      name: website-network
