<div class="page affichePage"><div id="titre"><h1>TEST</h1>
<p>Ceci est la page de test !</p>
</div><div class="section">
<h2>Grec</h2>
<p>La mythologie grecque, c'est-à-dire l'ensemble organisé des mythes provenant de la Grèce antique, se développe au cours d'une très longue période allant de la civilisation mycénienne jusqu'à la domination romaine. La rencontre entre les Grecs et les Romains coïncide avec celle de la mythologie grecque et de la mythologie romaine : la première exerce une forte influence sur la seconde, qui ne s'y réduit pas pour autant. Longtemps après la disparition des religions grecque et romaine, la mythologie grecque est utilisée comme sujet d'inspiration par les artistes, et continue à l'être de nos jours.

La mythologie grecque nous est parvenue grâce à un vaste ensemble de textes dont les plus anciens sont les épopées d'Homère et les poèmes d'Hésiode, principalement la Théogonie, mais aussi par les arts picturaux comme la céramique ou par les monuments sacrés. L'ensemble de ces sources présente des généalogies et des récits qui forment un système doté d'une cohérence limitée. Les mythes grecs témoignent de la représentation que les anciens Grecs se faisaient du monde. Néanmoins, le statut de la mythologie grecque est complexe, car la mythologie dépasse le cadre de la religion. Les personnages et les événements mythiques rapportés par la tradition étaient pour les Grecs, du moins dans leurs grandes lignes, des réalités historiques relevant d'un passé lointain et servaient donc de base de travail aux historiens antiques. Dans le même temps, la mythologie fournit une ample source d'inspiration à la littérature et aux arts grecs antiques.</p>
</div>
<div class="section">
<h2>La suite...</h2>
<p>La religion grecque était fondée sur des rituels pratiqués en commun, mais ne reposait pas sur un texte sacré ou sur des dogmes, et il n'existait pas non plus de littérature proprement religieuse1. Des textes comme la Théogonie d'Hésiode et les épopées d'Homère ne sont donc pas des textes sacrés : ce sont des œuvres littéraires proposant une vision parmi d'autres de la création du monde et des généalogies divines, mais elles ne se proposent pas de dicter ce qu'il faudrait obligatoirement croire. Le lien entre littérature et religion s'établit plutôt par la composition de textes destinés à être déclamés lors de cérémonies religieuses (par exemple les hymnes de Pindare et, de façon plus indirecte, les textes des tragédies, comédies et drames satyriques, puisque les représentations théâtrales sont liées au culte de Dionysos). Les dieux et héros mythologiques pouvaient être évoqués dans des contextes non immédiatement liés au culte proprement dit. Mais il faut garder à l'esprit que la société grecque antique ne connaît aucune séparation entre un domaine propre à la religion et le reste de la société : au contraire, la religion est présente de manière diffuse dans tous les aspects de la vie sociale et politique.
L'absence de dogme ou de canon religieux n'est bien sûr pas synonyme d'absence de croyance. En Grèce antique, la piété (eusebeia), l'une des principales notions de la religion grecque antique, suppose de révérer les mêmes divinités que l'ensemble de la communauté : en introduire de nouvelles est un acte d'impiété, à moins que la cité ne les accepte officiellement, et il est tout aussi impie d'endommager les représentations des dieux ou leurs propriétés ou de parodier les rituels3. Mais dans le même temps, plusieurs cosmogonies et théogonies coexistent sans que cela ne pose de problème (Homère présente dans l’Iliade Océan et Téthys comme le couple primordial, tandis que la Théogonie d'Hésiode place le Chaos, puis Éros et Gaïa, aux origines du monde et qu'une secte comme l'orphisme propose encore une autre interprétation). Et la comédie grecque antique de l'époque classique peut librement représenter dieux et héros sous des traits grotesques en leur prêtant un comportement bouffon.

Toutes les divinités ayant reçu un culte en Grèce antique n'ont pas fait l'objet de récits mythiques. Certaines, comme la déesse Hestia, en sont pratiquement absentes4. De même, ni la place d'une divinité ou d'un héros dans la hiérarchie des puissances divines, ni l'abondance des récits qui lui sont consacrés, ne reflètent nécessairement l'importance réelle de son culte : ainsi Asclépios, quoique très inférieur à des divinités telles que son père Apollon, disposait d'un sanctuaire à Épidaure dont la renommée s'étendait à l'ensemble du monde grec5. Enfin, alors que la différence de statut entre les dieux et les héros est assez appuyée dans les récits, les cultes rendus à des héros (les cultes héroïques) différaient assez peu, dans leurs modalités, de ceux rendus aux dieux</p>
</div>
<div class="section">
<h2>Mythologie et arts figurés</h2>
<p>Les textes sont loin d'être les seuls vecteurs de la mythologie grecque : celle-ci est également très présente dans les arts figurés tels que la céramique et la sculpture. À toutes les époques, les Grecs vivent entourés de représentations qui s'y rattachent, qu'il s'agisse des monuments et des statues de l'espace public, ou des objets de la vie quotidienne dans leur espace privé. Les représentations figurées mettant en scène des sujets mythologiques ne doivent pas être considérées comme de simples illustrations des textes : bien au contraire, elles adaptent leur sujet au contexte et au public auquel elles se destinent, et inventent souvent des variantes qui ne sont pas attestées par ailleurs dans les textes. Les vases destinés à recevoir le vin, par exemple, représentent eux-mêmes des banquets ou des scènes mythologiques liées à Dionysos, qui ne peuvent être comprises que si on les replace dans ce contexte du banquet grec13 ; ils mettent volontiers en scène des figures comme les satyres, qui sont assez peu présents par ailleurs dans les textes, mais qui apparaissent très souvent sur les vases dans des scènes typiques14. Ainsi, les arts figurés disposent eux aussi d'une grande liberté d'innovation ou de réinvention des mythes, et mettent en place leurs propres codes et conventions pour les représenter.</p>
</div>
<p>Ecrit par <i>Jeremie Henrion</i></p></div>